Update create-repos.yml

diff --git a/.github/workflows/create-repos.yml b/.github/workflows/create-repos.yml
--- a/.github/workflows/create-repos.yml
+++ b/.github/workflows/create-repos.yml
@@ -40,7 +40,11 @@ jobs:
               -d "{\"name\":\"$repository_name\",\"description\":\"This is your first repository\",\"private\":false,\"has_issues\":false,\"has_projects\":false,\"has_wiki\":false}"
             
             repo_index=$(jq -r --arg repo_name "$repository_name" '.repositories | map(.repo_name == $repo_name) | index(true)' $JSON)
-            echo "repository index: $repo_index"
+            echo "Repository index for $repository_name: $repo_index"
+            if [ "$repo_index" == "null" ]; then
+              echo "Error: Repository index not found for $repository_name. Check JSON file."
+              exit 1
+            fi
 
             # for repo_env_info in $(jq -c ".repositories[$repo_index].environments[]" $JSON); do
             #   env_name=$(echo "$repo_env_info" | jq -r '.env_name')
